/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Map(props) {
  const { nodes, materials } = useGLTF('/cityblendoptimized.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -8.061]} rotation={[-Math.PI / 2, 0, 0]} scale={0.315}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_05_Roof2_0.geometry}
            material={materials['05_Roof2.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_04_Roof1_0.geometry}
            material={materials['04_Roof1.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube037_03_Wood_0.geometry}
            material={materials['03_Wood.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube038_02_Window_0.geometry}
            material={materials['02_Window.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075_06_Front_0.geometry}
            material={materials['06_Front.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076_07_Beams_0.geometry}
            material={materials['07_Beams.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube077_08_Base_0.geometry}
            material={materials['08_Base.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube105_01_Frame_0.geometry}
            material={materials['01_Frame.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group position={[-0.671, 0.086, 3.057]} rotation={[-Math.PI / 2, 0, 0]} scale={0.302}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-122.326, 17.131, 0.43]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object008_������001_0'].geometry}
              material={materials['.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object008_������_0'].geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
      <group position={[6.137, 0.098, -0.958]} rotation={[-Math.PI / 2, 0, 0]} scale={0.227}>
        <group position={[2.909, -1.071, 4.833]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[-0.091, -1.071, 4.833]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[-3.091, -1.071, 4.833]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[-6.091, -1.071, 4.833]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[-6.091, -1.071, 8.333]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[-3.091, -1.071, 8.333]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[-0.091, -1.071, 8.333]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[2.909, -1.071, 8.333]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_1.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_2.geometry}
            material={materials['Material.008']}
          />
        </group>
        <group position={[2.909, -0.9, 1.1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_0.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Material.004']}
          />
        </group>
        <group position={[2.914, 4.281, 5.536]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_1.geometry}
            material={materials['Material.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_2.geometry}
            material={materials['Material.004_B_1']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_3.geometry}
            material={materials['Material.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_4.geometry}
            material={materials['Material.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_5.geometry}
            material={materials['Material.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_6.geometry}
            material={materials['Material.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_7.geometry}
            material={materials['Material.014']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_0.geometry}
          material={materials['material.001']}
          position={[6.049, -0.276, 4.204]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_0.geometry}
          material={materials['material.001']}
          position={[6.049, -0.276, 5.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_0.geometry}
          material={materials['Material.013']}
          position={[-8.305, -0.974, 11.875]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_0.geometry}
          material={materials['material.001']}
          position={[9.454, 4.699, 5.613]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_0.geometry}
          material={materials['material.001']}
          position={[10.779, 4.699, 5.613]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_0.geometry}
          material={materials['material.001']}
          position={[10.791, 6.509, 5.613]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_0.geometry}
          material={materials['material.001']}
          position={[5.794, 8.331, 8.605]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_0.geometry}
          material={materials['material.001']}
          position={[9.454, 6.509, 5.613]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_0.geometry}
          material={materials['material.001']}
          position={[-3.13, 8.599, 10.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle011_0.geometry}
          material={materials['material.001']}
          position={[-0.101, 8.597, 10.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_0.geometry}
          material={materials['material.001']}
          position={[6.062, -0.261, 4.211]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_0.geometry}
          material={materials['material.001']}
          position={[6.062, -0.261, 5.377]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_0.geometry}
          material={materials['material.001']}
          position={[9.466, 4.705, 5.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_0.geometry}
          material={materials['material.001']}
          position={[10.79, 4.705, 5.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_0.geometry}
          material={materials['material.001']}
          position={[10.802, 6.515, 5.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_0.geometry}
          material={materials['material.001']}
          position={[5.776, 8.339, 8.589]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_0.geometry}
          material={materials['material.001']}
          position={[9.466, 6.515, 5.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_0.geometry}
          material={materials['material.001']}
          position={[-3.173, 8.587, 10.891]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_0.geometry}
          material={materials['material.001']}
          position={[-0.058, 8.608, 10.901]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_0.geometry}
          material={materials['Material.003']}
          position={[6.909, 0.95, 1.761]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_0.geometry}
          material={materials['Material.003']}
          position={[8.909, 0.95, 1.761]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_0.geometry}
          material={materials['Material.003']}
          position={[10.909, 0.95, 1.761]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_0.geometry}
          material={materials['Material.003']}
          position={[12.909, 0.95, 1.761]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_0.geometry}
          material={materials.material_11}
          position={[5.939, 4.51, 9.316]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_0.geometry}
          material={materials.material_11}
          position={[5.542, 4.51, 11.573]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_0.geometry}
          material={materials.material_11}
          position={[14.949, 9.08, 2.286]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_0.geometry}
          material={materials.material_11}
          position={[5.939, 4.51, 6.126]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_0.geometry}
          material={materials.material_11}
          position={[14.552, 9.08, 6.065]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_0.geometry}
          material={materials.material_11}
          position={[14.949, 9.08, 4.633]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_0.geometry}
          material={materials['s.001']}
          position={[2.86, 4.484, 17.228]}
        />
      </group>
      <group position={[-1.135, 0.173, -1.114]} rotation={[-Math.PI / 2, 0, 0]} scale={0.068}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Epiphany_Monastery_Cross_0.geometry}
              material={materials.Cross}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Epiphany_Monastery_Dome_0.geometry}
              material={materials.Dome}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Epiphany_Monastery_Epiphany_Mat_0.geometry}
              material={materials.Epiphany_Mat}
            />
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
      />
    </group>
  )
}

useGLTF.preload('/cityblendoptimized.glb')
