// This file is generated by npm run build:icons
 
export type IconName =
	| "dogWalk/dogWalk/background"
	| "dogWalk/dogWalk/backgroundOptimized"
	| "dogWalk/dogWalk/dog-walk"
	| "dogWalk/dogWalk/foreground"
	| "dogWalk/dogWalk/midground"
	| "dogWalk/sprite"
	| "Frame 1"
	| "layered-waves-haikei"
	| "lucide/camera";
